# Banco H2
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:ninju;DB_CLOSE_DELAY=-1

# Recria as tabelas a cada inicialização
quarkus.hibernate-orm.database.generation=drop-and-create

# Console visual do H2 (acesse http://localhost:8080/h2-console em dev)
quarkus.datasource.devservices.enabled=false
%dev.quarkus.hibernate-orm.log.sql=true
quarkus.h2.console.enabled=true
quarkus.h2.console.path=/h2-console
quarkus.h2.console.web-allow-others=true

# CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*

# JWT
quarkus.smallrye-jwt.enabled=true
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=ninju
smallrye.jwt.sign.key.location=privateKey.pem