# Manda o Quarkus usar o banco H2
quarkus.datasource.db-kind=h2

# Manda o Hibernate criar as tabelas das nossas Entities toda vez que o app rodar
quarkus.hibernate-orm.database.generation=drop-and-create