# Banco H2
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:ninju

# Recria as tabelas a cada inicialização
quarkus.hibernate-orm.database.generation=drop-and-create

# Console visual do H2 (acesse http://localhost:8080/h2-console em dev)
quarkus.h2.console.enabled=true

# JWT
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=ninju
smallrye.jwt.sign.key.location=privateKey.pem